Fix an position
nomalab/subtitle pull request #63
Opened 2023-05-16 13:13 UTC by oupen

nomalab/nomalab#4623

2023-05-30 13:51 UTC, Romanelaf requested changes

2023-05-30 13:51 UTC, Romanelaf commented on src/main/java/fr/noop/subtitle/srt/SrtParser.java
> +                    region.setVerticalPosition(1);
pas besoin de set la vertical position, c'est pour les stl à la base, le VerticalAlign.TOP suffit pour les autres formats

2023-05-30 15:32 UTC, oupen commented on src/main/java/fr/noop/subtitle/srt/SrtParser.java
> +                    region.setVerticalAlign(SubtitleRegion.VerticalAlign.BOTTOM);
comme ça ?

2023-05-31 08:06 UTC, oupen commented on src/main/java/fr/noop/subtitle/srt/SrtParser.java
> +                    region.setVerticalAlign(SubtitleRegion.VerticalAlign.BOTTOM);
ah  oui je vois

2023-05-31 08:57 UTC, Romanelaf approved these changes

2023-05-31 10:07 UTC, merged